FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Команда запуска для Streamlit
CMD streamlit run app.py --server.port $PORT --server.address 0.0.0.0